# Generated by Django 5.2 on 2025-04-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
