# Generated by Django 5.2 on 2025-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_restaurant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
