# Generated by Django 5.2 on 2025-09-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_fooditemreview_restaurantreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
