# Generated by Django 5.2 on 2025-09-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_remove_restaurantreview_restaurant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='photo',
            new_name='image',
        ),
    ]
